# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:
        enabled: true
        force: true
    view:
        mime_types:
            enabled: true
            formats:
                json: ['application/json', 'application/json;version=1.0', 'application/json;version=2.0']
        formats: { json: true, xml: false, rss: false }
        view_response_listener:
            enabled: true
            force: true
    serializer:
        serialize_null: false
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            'App\Exception\ResourceValidationException': 400
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
        messages:
            'App\Exception\ResourceValidationException': true
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    versioning:
        enabled: true
        default_version: '1.0'
        resolvers:
            media_type:
                enabled: true
                regex: /(v|version)=(?P<version>[0-9\.]+)/
