# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener:
            enabled: true
            force: true
    serializer:
        serialize_null: true
    body_converter:
        enabled: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
