register:
    path: /register
    controller: App\Controller\DefaultController::register
    methods: POST

login_check:
    path: /login_check
    methods:  [POST]

# homepage:
#     path: /
#     controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
#     defaults:
#         path: /login_check
#         permanent: true
